version: "2"
services: 
  web:
    build: .
    environment:
      - MONGO_SERVER=mongo
    ports:
      - "8080:8080"
    links:
      - mongo

  mongo:
      image: mongo
      ports:
        - "27017:27017"